### ISSUE TITLE
Support sending data over TCP

### ISSUE THREAD

**Issue by jmhodges** [cactus/go-statsd-client#14]
Statsd provides a TCP based API. It is preferable for many to use it because using UDP for sending metrics will cause loss of metrics for the hosts that you [most want data from](https://twitter.com/aphyr/status/563428098461270016).

**Comment by cactus** [comment]
As statsd metrics are generally heavily sampled, I am admittedly dubious that tcp in combination with client-to-statsd is a great solution (statsd already sends collated metrics to graphite via tcp). A tcp client would also have to be more complex, and any "backpressure" would also result in dropped and/or heavily delayed metrics, so again unsure of the overall benefit.

If you need far more robust metrics, and better ability to deal with failure scenarios, then you may want aggregate and sample locally within the app, and send directly to graphite via tcp (see [graphite-golang](https://github.com/marpaia/graphite-golang). Another option may be to use something like [go-metrics](https://github.com/rcrowley/go-metrics) and a pull-based metrics system like [prometheus](http://prometheus.io) or [reconnoiter](https://github.com/circonus-labs/reconnoiter).

However, in order to avoid succumbing to a knee-jerk dismissal, I will think it over for a while. My overall concern is not whether I think it is a good or bad idea, per se, as the user can certainly decide that for themselves. My concern is long term maintenance of a feature that I will personally not use and thus may get little testing.

**Comment by cactus** [comment]
@jmhodges I have been playing with a [branch](/cactus/go-statsd-client/tree/tcp-testing). I am still concerned that if the server goes away though, the statds sender will either lock up (and impact the app using it), or simply start returning err's to the caller. This places a burden on the caller to recreate (safely!) the client (to reconnect) when the server once again comes back up -- if it ever does.

I think it would be safer to have a udp endpoint listening over loopback that itself uses tcp to send to graphite or statsd, instead of trying to bake that extra complexity into the client.

Let me know if you have any other thoughts on the matter, or if you have ideas for handling the failure scenarios in a clean (and optimally with relatively low overhead) way.

I will fiddle with this branch a bit more and see if I end up with feeling any better about it.

**Comment by cactus** [comment]
Closing for now. I will leave the branch in case anyone wants to use it.
