### ISSUE TITLE
Negative gauge values interpreted as deltas

### ISSUE THREAD

**Issue by mmcloughlin** [cactus/go-statsd-client#16]
Two calls to `Gauge` with the values -1 and -2 will result in the metric having value -3, not -2 as intended.

This is really statsd's fault, as noted at https://github.com/etsy/statsd/blob/master/docs/metric_types.md#gauges where it says "This implies you can't explicitly set a gauge to a negative number without first setting it to zero."

I suggest that the `Gauge` implementation should set the metric to zero first when the desired value is negative.

I am happy to work on a PR if you think this is a good idea.

**Comment by cactus** [comment]
@mmcloughlin 

> I suggest that the Gauge implementation should set the metric to zero first when the desired value is negative.

How would the code know when it was appropriate to do so? 

Even if you assume you always send 0 the first time a gauge is seen (say, with a state flag and a mutex), you could never know the current state of the statsd server. If the statsd server was restarted (administratively or from a crash) the app sending code would not know to send zeros again.

I think this really needs to be solved by the statsd server.

However, I would certainly be happy to add some documentation regarding this issue to the api docs, if you think it would be helpful to folks.

**Comment by mmcloughlin** [comment]
*Every time* a gauge is set to a negative value it needs to be preceded by a line setting the gauge to zero.

Using the example of calling `Gauge` with -1 and -2, the current behavior will result in the following lines being sent to the server. Suppose the original value of `metric` is 0, then I've shown the new values of gauge in the second column

```
metric:-1|g    -1
metric:-2|g    -3
```

I propose that these two calls actually produce the following lines:

```
metric:0|g      0
metric:-1|g    -1
metric:0|g      0
metric:-2|g    -2
```

If preceded by a line setting `metric` to zero, the delta will set the gauge to the right value.

The problem is if the two lines are not processed atomically. If a statsd flush falls between the call to set to zero and the delta, then the gauge value will be published as zero. Are multi-metric packets processed atomically?

**Comment by cactus** [comment]
Ah. So adding zeros before *all* negative gauges. I suppose the added traffic isn't the worst thing in the world (even though it is a bummer), as long as it is optional. Some people may **want** the current behavior of `-1` subtracting from the current gauge, as `+1` is additive . Some implementations appear to not even support negative gauges (statsdaemon is one), and only ever use `+` and `-` prefix for gauges as relative changes.

> Are multi-metric packets processed atomically?

**If you are asking about go-statsd-client internals...**

If you are not using a buffered sender, you could certainly see some out of order processing occur at the statsd side. Lets say you send a 0 and a -1 (separate packets). If the server restarts and misses the 0 packet, but sees the -1 packet, then it would start off processing incorrectly. A subsequent 0 would "reset" the gauge so the window of falsehood would be very small.

For a multimetric packet (buffered client) you would have to be careful not to reach max packet size after the 0 line, but before the -1 metric. It might take a bit of extra logic there to avoid that situation -- since the metrics come in via a channel and are processed one at a time. 

This could be solved by lumping the two metrics together and splitting later on newline if not using a buffered writer. Would have to think about it though. Might require some refactoring.

**If you are asking about the statsd side though...**

I think it depends on the implementation. Some implementations (statsdaemon for example), do process packets in parallel (multiple senders can have multimetric packets processing in parallel if gomaxprocs>1). Node is single threaded though, so my guess is the reference implementation processes individual udp packets in series (while other udp packets wait in the socket buffer).

**Comment by cactus** [comment]
Closing for now. I think this is best handled in the sending app itself.
Reopen if you wish to discuss further.
