### ISSUE TITLE
Question about locking mechanism

### ISSUE THREAD

**Issue by shsing2000** [cactus/go-statsd-client#20]
I have a general question about the locking mechanism and was wondering if you could shed light on your intentions around this:
https://github.com/cactus/go-statsd-client/blob/master/statsd/sender_buffered.go#L64-L69

Specifically, what kind of situation are you protecting against with the read lock?

Thanks in advance.

**Comment by cactus** [comment]
Specifically, protection against mutation of s.running while reading that same value. Granted, it is certainly a very edge case -- the user would have to *not* use NewBufferedSender, and instead be constructing their own sender, and calling start unsafely in more than one goroutine. I still wanted to guard against it though.

Looking at the code again, there could possibly still be an issue between the unlocking of the read lock, and the acquiring of the write lock. The code should probably check s.running again after acquiring the write lock.

**Comment by cactus** [comment]
If your question was why even use a read lock there, instead of always just grabbing a write lock... I guess it was just because Send was using a "read lock and test", so I did the same there. It might indeed be more straightforward to always just acquire a write lock for start and close.

If you want to make that change as a pull request, I would accept it.

**Comment by cactus** [comment]
closing
