### ISSUE TITLE
Statter suggests it's not sampled

### ISSUE THREAD

**Issue by falun** [cactus/go-statsd-client#28]
In my poking around for https://github.com/cactus/go-statsd-client/issues/27 I noticed that the `Statter` interface doesn't expose `SetSamplerFunc` -- is there any reason for this?

If there isn't it seems reasonable to reflect that the base `Statter` also has a sampler that can be configured.

**Comment by cactus** [comment]
It was intentional, yes. If an app exported a statsd client for plugins to use, for example, you wouldn't want to allow too much customization of the base client, as it would impact all instances of it. However, a substatter is more localized (a plugin can create a substatter and modify the inherited sampler).

It was added base don #24, if you want to read the background. I am not sure how widely utilized it is, so indeed the usage may be a bit awkward. 

As far as a workaround, you could always type assert a Statter to a Client (if it happens to be one) or Substatter,  and then set the sampler that way. Not great used directly, but maybe palatable if you have a wrapper creating a Statter and returning it.

**Comment by falun** [comment]
Yea, for general use it's not much of a problem / is easy to work around. It just made the static sampling wrapper a bit weirder to build but that's not really a common use case :)

Anyway, was just wondering if there was intent; thanks for humoring me.
