### ISSUE TITLE
is there a way to pass tags?

### ISSUE THREAD

**Issue by dcu** [cactus/go-statsd-client#38]
like this:

https://github.com/DataDog/datadog-go/blob/master/statsd/statsd.go#L176

**Comment by cactus** [comment]
No, the "non-stadard" DataDog tag functionality is not currently supported. It looks like the DataDog specific library appends "|#" then a list of comma separated tags to the end of the element. Being at the end means that StatSender.Raw wouldn't work (because it puts the rate at the end). Aside: I'm not even sure if the DataDog tag extension existed when I first started this library back in 2012.

It wouldn't be terribly difficult to add such support, but it **would** be a breaking change for the Statter/StatSender interface definition and the currently exported api. Given the limited scope of usage (only DataDog customers?), I am resistant to breaking it for anyone else building upon the library. The non-breaking change alternative would require duplication of quite a bit of code to maintain backwards compatibility.

So if tag support is necessary for your usage, and the DataDog client is not meeting your needs (performance, compatability, etc), then I would recommend either finding another library that supports what you need, or forking this library and specifically adding that functionality to your fork. 

To add tag support, I think you would need to do the following:
* Update the StatSender interface to add a `[]string tags` param for each method
* Update each method to accept the `[]string tags` param and pass it to `s.submit`
* Update `submit` to accept the `[]string tags` param, and then append that list of tags to the byte buffer right before the call to `s.sender.Send`.

**Comment by cactus** [comment]
Closing for now. Reopen if you wish to continue the discussion.

**Comment by SleepyBrett** [comment]
stripe's veneur also supports dogstatsd style tagging.
