### ISSUE TITLE
Review incorrect go module usage

### ISSUE THREAD

**Issue by cep21** [cactus/go-statsd-client#43]
Hi,

I ran into the following issue using this client with go and modules.

```
build github.com/my/service: cannot load github.com/cactus/go-statsd-client/statsd: ambiguous import: found github.com/cactus/go-statsd-client/statsd in multiple modules:
    github.com/cactus/go-statsd-client v3.1.1+incompatible (/Users/jlindamo/go/pkg/mod/github.com/cactus/go-statsd-client@v3.1.1+incompatible/statsd)
    github.com/cactus/go-statsd-client/statsd v0.0.0-20190501063751-9a7692639588 (/Users/jlindamo/go/pkg/mod/github.com/cactus/go-statsd-client/statsd@v0.0.0-20190501063751-9a7692639588)
```

This doesn't happen if you're directly referencing this client, but can if multiple libraries are referencing the client in different ways and you're trying to use both libraries at once.

I don't think the change to add the go.mod file was correct: https://github.com/cactus/go-statsd-client/blob/master/statsd/go.mod

With go.mod, since you're on tag v3, the path of everything inside there should be `github.com/cactus/go-statsd-client/statsd/v3` instead of `github.com/cactus/go-statsd-client/statsd`.  That includes the go.mod file as well.

It may be best to either add `v3` to the path in the module file, or remove the go.mod file.

**Comment by cep21** [comment]
CC: @manaspaldhe12

**Comment by cactus** [comment]
There is some unclear documentation on the go site in regards to the placement of go.mod.
For example,  [this documentation wiki](https://github.com/golang/go/wiki/Modules#gomod) makes it sound like like even though the go-statsd-client is never used as a top level import (eg. `import "github.com/cactus/go-statsd-client"`) that the go.mod should go at the top level anyway. That's a bit strange... 

[This page](https://golang.org/cmd/go/#hdr-Defining_a_module) seems to present conflicting information:
> A module is defined by a tree of Go source files with a go.mod file in the tree's root directory. The directory containing the go.mod file is called the module root. **Typically** the module root will also correspond to a source code repository root (**but in general it need not**). The module is the set of all Go packages in the module root and its subdirectories, but excluding **subtrees with their own go.mod files**.

Perhaps you can post the go.mod for the project that raised the error? 
Maybe that go.mod file has a dep pinned for `github.com/cactus/go-statsd-client` instead of for `github.com/cactus/go-statsd-client/statsd`?

**Comment by cactus** [comment]
no feedback. closing for now. reopen if needed.
